# -*- coding: utf-8 -*-
"""Citra Digital.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eo0CzTDGvvYRnoJWry3GPWZsTuWCEn_8
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files

# Upload gambar
uploaded = files.upload()

# Ambil nama file
image_path = list(uploaded.keys())[0]

# Baca gambar
img = cv2.imread(image_path)
img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

plt.imshow(img_rgb)
plt.title("Original Image")
plt.axis('off')

gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)

plt.imshow(gray, cmap='gray')
plt.title("Grayscale")
plt.axis('off')

_, binary = cv2.threshold(gray, 127, 255, cv2.THRESH_BINARY)

plt.imshow(binary, cmap='gray')
plt.title("Binary Image")
plt.axis('off')

m = 4  # jumlah bit
levels = 2**m
gray_mbit = np.floor(gray / (256/levels)) * (256/levels)
gray_mbit = gray_mbit.astype(np.uint8)

plt.imshow(gray_mbit, cmap='gray')
plt.title(f"{m}-bit Image")
plt.axis('off')

brightness = 50
bright_img = cv2.add(gray, brightness)

plt.imshow(bright_img, cmap='gray')
plt.title("Brightness Image")
plt.axis('off')

alpha = 1.5  # kontras
contrast_img = cv2.convertScaleAbs(gray, alpha=alpha, beta=0)

plt.imshow(contrast_img, cmap='gray')
plt.title("Contrast Image")
plt.axis('off')

plt.hist(gray.ravel(), bins=256, range=[0,256])
plt.title("Histogram Grayscale")
plt.xlabel("Pixel Value")
plt.ylabel("Frequency")

equalized = cv2.equalizeHist(gray)

plt.imshow(equalized, cmap='gray')
plt.title("Histogram Equalization")
plt.axis('off')

# Histogram setelah equalization
plt.figure()
plt.hist(equalized.ravel(), bins=256, range=[0,256])
plt.title("Histogram Equalized")